### ISSUE TITLE
ERROR RECEIVING IMAGES

### ISSUE THREAD

**Issue by SaadeMotion** [danielcardeenas/whatsapp-framework#105]
I was receiving a image, when this occured:

```
Unhandled exception in thread started by <bound method YowStack.loop of <yowsup.stacks.yowstack.YowStack object at 0x7f6e34613e10>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/stacks/yowstack.py", line 196, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.6/asyncore.py", line 188, in poll2
    readwrite(obj, flags)
  File "/usr/lib/python3.6/asyncore.py", line 123, in readwrite
    obj.handle_error()
  File "/usr/lib/python3.6/asyncore.py", line 108, in readwrite
    obj.handle_read_event()
  File "/usr/lib/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 46, in receive
    self.onMessage(protocolTreeNode)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 80, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 93, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 137, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 221, in parseAndHandleMessageProto
    self.handleImageMessage(node, m.image_message)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 282, in handleImageMessage
    self.toUpper(messageNode)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/protocol_media/layer.py", line 44, in recvMessageStanza
    self.toUpper(entity)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/interface/interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "/home/saademotion/Projects/whatsapp-poll/app/layer.py", line 72, in on_message
    message = Message(message_entity)
  File "/home/saademotion/Projects/whatsapp-poll/app/models/message.py", line 18, in __init__
    self.build()
  File "/home/saademotion/Projects/whatsapp-poll/app/models/message.py", line 24, in build
    self.build_media_message()
  File "/home/saademotion/Projects/whatsapp-poll/app/models/message.py", line 42, in build_media_message
    self.file_path = downloader.get_file(self.message_entity)
  File "/home/saademotion/Projects/whatsapp-poll/app/utils/downloader.py", line 13, in get_file
    out_file = decrypt_file(message_entity, enc_path)
  File "/home/saademotion/Projects/whatsapp-poll/app/utils/downloader.py", line 40, in decrypt_file
    out = os.path.splitext(enc_path)[0] + '.jpg'
  File "/usr/lib/python3.6/posixpath.py", line 120, in splitext
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

I guess the .enc file is wrong/not exist/corrupted or something, please, can you take a look? :)

many thanks

**Comment by NarutoInstinct** [comment]
I also receive an error when receiving an image:
```
Error occured at transfer
Traceback (most recent call last):
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\protocol_media\mediadownloader.py", line 26, in download
    os.makedirs(os.path.dirname(path), exist_ok=True)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 239, in dirname
    return split(p)[0]
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 211, in split
    head = head.rstrip(seps) or head
AttributeError: 'list' object has no attribute 'rstrip'
Traceback (most recent call last):
  File "run.py", line 57, in <module>
    c.start()
  File "run.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\stacks\yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\asyncore.py", line 150, in poll
    read(obj)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 46, in receive
    self.onMessage(protocolTreeNode)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 80, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 95, in handleEncMessage
    self.handleWhisperMessage(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 153, in handleWhisperMessage
    self.parseAndHandleMessageProto(encMessageProtocolEntity, plaintext[:-padding])
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 221, in parseAndHandleMessageProto
    self.handleImageMessage(node, m.image_message)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\axolotl\layer_receive.py", line 282, in handleImageMessage
    self.toUpper(messageNode)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 194, in receive
    s.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 130, in receive
    recv(node)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\protocol_media\layer.py", line 44, in recvMessageStanza
    self.toUpper(entity)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\site-packages\yowsup2-2.5.2-py3.5.egg\yowsup\layers\interface\interface.py", line 80, in receive
    self.entity_callbacks[entityType](entity)
  File "c:\Users\Dell\Desktop\Stage Jules\mac\app\layer.py", line 72, in on_message
    message = Message(message_entity)
  File "c:\Users\Dell\Desktop\Stage Jules\mac\app\models\message.py", line 18, in __init__
    self.build()
  File "c:\Users\Dell\Desktop\Stage Jules\mac\app\models\message.py", line 24, in build
    self.build_media_message()
  File "c:\Users\Dell\Desktop\Stage Jules\mac\app\models\message.py", line 42, in build_media_message
    self.file_path = downloader.get_file(self.message_entity)
  File "c:\Users\Dell\Desktop\Stage Jules\mac\app\utils\downloader.py", line 13, in get_file
    out_file = decrypt_file(message_entity, enc_path)
  File "c:\Users\Dell\Desktop\Stage Jules\mac\app\utils\downloader.py", line 40, in decrypt_file
    out = os.path.splitext(enc_path)[0] + '.jpg'
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\ntpath.py", line 224, in splitext
    return genericpath._splitext(p, '\\', '/', '.')
  File "C:\Users\Dell\AppData\Local\Programs\Python\Python35\lib\genericpath.py", line 118, in _splitext
    sepIndex = p.rfind(sep)
AttributeError: 'NoneType' object has no attribute 'rfind'
```
Our tracebacks seems similiar, so I guess my error is somewhat related. I'll gladly hear if someone finds a fix ^^
