### ISSUE TITLE
can't register with yowsup-cli in the instruction

### ISSUE THREAD

**Issue by OVAnechka** [danielcardeenas/whatsapp-framework#112]
yowsup-cli  v2.0.15
yowsup      v2.5.2

Here's a stacktrace

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 189, in process
    self.handleRequestCode(self.args["requestcode"], config)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 208, in handleRequestCode
    result = codeReq.send()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/registration/coderequest.py", line 62, in send
    res = super(WACodeRequest, self).send(parser)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/common/http/warequest.py", line 70, in send
    return self.sendGetRequest(parser)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/common/http/warequest.py", line 108, in sendGetRequest
    self.response = WARequest.sendRequest(host, port, path, headers, params, "GET")
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/common/http/warequest.py", line 164, in sendRequest
    conn.request(reqType, path, params, headers);
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 1400, in connect
    server_hostname=server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 401, in wrap_socket
    _context=self, _session=session)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 808, in __init__
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 1061, in do_handshake
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

**Comment by hiteshjoshi** [comment]
same for me

**Comment by zeegb** [comment]
same for me

**Comment by imansdn** [comment]
This is sloved my problem..
`
cd /Applications/Python\ 3.7/
./Install\ Certificates.command
`
