### ISSUE TITLE
Can't run

### ISSUE THREAD

**Issue by edmund7s** [danielcardeenas/whatsapp-framework#15]
Dear Daniel,

Thanks for the this great project and I'm excited.  But I'm having problem while running the run.py

I've been looking yowsup module and I couldn't find a function called signals.

Can you help please?

> Traceback (most recent call last):
  File "/home/e7s/PycharmProjects/WAbot/whatsapp-framework-master/run.py", line 9, in <module>
    from app.layer import MacLayer
  File "/home/e7s/PycharmProjects/WAbot/whatsapp-framework-master/app/layer.py", line 9, in <module>
    from app.intercepter import intercepter
  File "/home/e7s/PycharmProjects/WAbot/whatsapp-framework-master/app/intercepter/intercepter.py", line 1, in <module>
    from yowsup import signals as yowsup_singals
ImportError: cannot import name 'signals'

**Comment by danielcardeenas** [comment]
You have to compile my version yowsup fork.
Just run `sudo ./setup.sh` ad described in the `README.md`
