### ISSUE TITLE
Unkown ib node <ib from="s.whatsapp.net">

### ISSUE THREAD

**Issue by msrahmanian** [danielcardeenas/whatsapp-framework#166]
Hello
Thank you for developing this framework while most of people stopped their support in whatsapp protocol,
I completely installed your framework on my Centos7.2 and python 3.5 and recieved both sms and my password, then I set the login and password and also some contacts in my config.py . when I run start.py command, I face to this error ,

Whatsapp bot crashed with code 1.  Respawning..
[Whatsapp] Mac started

Traceback (most recent call last):
  File "run.py", line 57, in <module>
    c.start()
  File "run.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib64/python3.6/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib64/python3.6/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib64/python3.6/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib64/python3.6/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib64/python3.6/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_receive.py", line 49, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/__init__.py", line 130, in receive
    recv(node)
  File "/usr/lib/python3.6/site-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/protocol_ib/layer.py", line 27, in recvIb
    raise ValueError("Unkown ib node %s" % node)
ValueError: Unkown ib node <ib from="s.whatsapp.net">
<fbip>
18.196.234.57|5222|1528798790|90000|false|false,54.88.13.5|5222|1528798790|90000|false|false
HEX3:b'31382e3139362e3233342e35377c353232327c313532383739383739307c39303030307c66616c73657c66616c73652c35342e38382e31332e357c353232327c313532383739383739307c39303030307c66616c73657c66616c7365'
</fbip>
</ib>

**Comment by javad329** [comment]
Same problem
