### ISSUE TITLE
Notes for Debian stable / Notas para la instalacion en debian estable

### ISSUE THREAD

**Issue by azacchino** [danielcardeenas/whatsapp-framework#17]
**Español**

En debian pip3.5 es llamado directamente pip3, por lo que hay q modificar la linea 10 del setup.sh

Al ejecutar start.sh se evidencian algunas dependencias faltantes. 
Primero creá el archivo ffmpegdw.py con el siguiente contenido
``` py
import imageio
imageio.plugins.ffmpeg.download()
```
y luego ejecutá los siguientes comandos como root
``` sh
# python3.5 -m pip install moviepy
# python3.5 ffmpegdw.py
```

**English** 
pip3.5 is called pip3 on debian stable, Please modify the line 10 in setup.sh file.

Dependences missing executing start.sh:
first create the file ffmpegdw.py and put this on them.
``` py
import imageio
imageio.plugins.ffmpeg.download()
```
Next run (as root)
``` sh
# python3.5 -m pip install moviepy
# python3.5 ffmpegdw.py
```

**Comment by danielcardeenas** [comment]
I did this to ensure Python3.5, however I don't remember any version of Python 3 being a problem soo I changed that line as you said.

**Comment by azacchino** [comment]
The log for this two errors  // El log de estos errores (por si te sirve de algo)

``` sh
root@debian:/home/me/whatsapp-framework# ./setup.sh              Installing yowsup libraries
--------------------------
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
yowsup.common.__pycache__.tools.cpython-35: module references __file__
--------------------------
Configuring modules
--------------------------
[\033[0;36melo\033[0m] Installing dependencies...
./setup.sh: line 10: pip3.5: command not found
Error:[127]. Try running it with root privilages
root@debian:/home/me/whatsapp-framework# pip
pip     pip2    pip2.7  pip3
root@debian:/home/me/whatsapp-framework# pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
```

``` sh
root@debian:/home/me/whatsapp-framework# ./start.sh
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from app.layer import MacLayer
  File "/home/me/whatsapp-framework/app/__init__.py", line 1, in <module>
    import modules
  File "/home/me/whatsapp-framework/modules/__init__.py", line 3, in <module>
    from modules.yesno import yesno
  File "/home/me/whatsapp-framework/modules/yesno/__init__.py", line 2, in <module>
    from modules.yesno.yesno import YesNo
  File "/home/me/whatsapp-framework/modules/yesno/yesno.py", line 2, in <module>
    import moviepy.editor as mp
ImportError: No module named 'moviepy'
```
y despues de instalar el modulo. 
and after install moviepy with pip

``` sh
root@debian:/home/me/whatsapp-framework# ./start.sh
Traceback (most recent call last):
  File "run.py", line 9, in <module>
    from app.layer import MacLayer
  File "/home/me/whatsapp-framework/app/__init__.py", line 1, in <module>
    import modules
  File "/home/me/whatsapp-framework/modules/__init__.py", line 3, in <module>
    from modules.yesno import yesno
  File "/home/me/whatsapp-framework/modules/yesno/__init__.py", line 2, in <module>
    from modules.yesno.yesno import YesNo
  File "/home/me/whatsapp-framework/modules/yesno/yesno.py", line 2, in <module>
    import moviepy.editor as mp
  File "/usr/local/lib/python3.5/dist-packages/moviepy/editor.py", line 22, in <module>
    from .video.io.VideoFileClip import VideoFileClip
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/VideoFileClip.py", line 3, in <module>
    from moviepy.video.VideoClip import VideoClip
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/VideoClip.py", line 21, in <module>
    from .io.ffmpeg_writer import ffmpeg_write_image, ffmpeg_write_video
  File "/usr/local/lib/python3.5/dist-packages/moviepy/video/io/ffmpeg_writer.py", line 11, in <module>
    from moviepy.config import get_setting
  File "/usr/local/lib/python3.5/dist-packages/moviepy/config.py", line 35, in <module>
    FFMPEG_BINARY = get_exe()
  File "/usr/local/lib/python3.5/dist-packages/imageio/plugins/ffmpeg.py", line 86, in get_exe
    raise NeedDownloadError('Need ffmpeg exe. '
imageio.core.fetching.NeedDownloadError: Need ffmpeg exe. You can download it by calling:
  imageio.plugins.ffmpeg.download()
```

Great framework! great job! tnk!

**Comment by danielcardeenas** [comment]
Igual deberia quitar moviepy porque no se esta usando por el momento. Pero tdeberias tener el binario de pip3.5 asi como tienes el de 2.7
