### ISSUE TITLE
send Image issue

### ISSUE THREAD

**Issue by umeshnaga** [danielcardeenas/whatsapp-framework#206]
hi
  i am sending image after send mail it show following error Please help me.

Error occured at transfer bytearray index out of range
Traceback (most recent call last):
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 165, in run
    self.successCallback(sourcePath, self.jid, result)
  File "/Users/uk/PycharmProjects/proj/app/mac/mac.py", line 266, in <lambda>
    caption)
  File "/Users/uk/PycharmProjects/proj/app/mac/mac.py", line 290, in do_send_media
    self.toLower(entity)
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 136, in send
    send(entity)
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/layer.py", line 36, in sendMessageEntity
    self.entityToLower(entity)
  File "/Users/umeshnaga/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 140, in entityToLower
    self.toLower(entity.toProtocolTreeNode())
  File "/Users/umeshnaga/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 84, in toLower
    self.__lower.send(data)
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/__init__.py", line 198, in send
    s.send(data)
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 114, in send
    self.handleEncNode(node)
  File "/Users/uk/PycharmProjects/whatsapp/BigTos/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 74, in handleEncNode
    ciphertext = sessionCipher.encrypt(messageData)
  File "/Users/uk/PycharmProjects/whatsapp/BigTos/lib/python3.5/site-packages/python_axolotl-0.1.39-py3.5.egg/axolotl/sessioncipher.py", line 49, in encrypt
    senderEphemeral = sessionState.getSenderRatchetKey()
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/python_axolotl-0.1.39-py3.5.egg/axolotl/state/sessionstate.py", line 66, in getSenderRatchetKey
    return Curve.decodePoint(bytearray(self.sessionStructure.senderChain.senderRatchetKey), 0)
  File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/python_axolotl-0.1.39-py3.5.egg/axolotl/ecc/curve.py", line 34, in decodePoint
    type = _bytes[0]  # byte appears to be automatically converted to an integer??
IndexError: bytearray index out of range

**Comment by umeshnaga** [comment]
> hi
> i am sending image after send mail it show following error Please help me.
> 
> Error occured at transfer bytearray index out of range
> Traceback (most recent call last):
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 165, in run
> self.successCallback(sourcePath, self.jid, result)
> File "/Users/uk/PycharmProjects/proj/app/mac/mac.py", line 266, in 
> caption)
> File "/Users/uk/PycharmProjects/proj/app/mac/mac.py", line 290, in do_send_media
> self.toLower(entity)
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/**init**.py", line 84, in toLower
> self.__lower.send(data)
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/**init**.py", line 198, in send
> s.send(data)
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/**init**.py", line 136, in send
> send(entity)
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/layer.py", line 36, in sendMessageEntity
> self.entityToLower(entity)
> File "/Users/umeshnaga/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/**init**.py", line 140, in entityToLower
> self.toLower(entity.toProtocolTreeNode())
> File "/Users/umeshnaga/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/**init**.py", line 84, in toLower
> self.__lower.send(data)
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/**init**.py", line 198, in send
> s.send(data)
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 114, in send
> self.handleEncNode(node)
> File "/Users/uk/PycharmProjects/whatsapp/BigTos/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 74, in handleEncNode
> ciphertext = sessionCipher.encrypt(messageData)
> File "/Users/uk/PycharmProjects/whatsapp/BigTos/lib/python3.5/site-packages/python_axolotl-0.1.39-py3.5.egg/axolotl/sessioncipher.py", line 49, in encrypt
> senderEphemeral = sessionState.getSenderRatchetKey()
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/python_axolotl-0.1.39-py3.5.egg/axolotl/state/sessionstate.py", line 66, in getSenderRatchetKey
> return Curve.decodePoint(bytearray(self.sessionStructure.senderChain.senderRatchetKey), 0)
> File "/Users/uk/PycharmProjects/whatsapp/proj/lib/python3.5/site-packages/python_axolotl-0.1.39-py3.5.egg/axolotl/ecc/curve.py", line 34, in decodePoint
> type = _bytes[0] # byte appears to be automatically converted to an integer??
> IndexError: bytearray index out of range
