### ISSUE TITLE
Whatsapp bot crashed with code 1.  Respawning..

### ISSUE THREAD

**Issue by camiu01** [danielcardeenas/whatsapp-framework#239]
i have start ./start.sh with su but it crash a little help?

File "run.py", line 56, in <module>
    c = MacStack()
  File "run.py", line 28, in __init__
    self.stack.setCredentials(credentials)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/stacks/yowstack.py", line 156, in setCredentials
    self.getLayerInterface(YowAuthenticationProtocolLayer).setCredentials(*credentials)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/auth/layer_interface_authentication.py", line 5, in setCredentials
    self._layer.setCredentials((phone, password))
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/auth/layer_authentication.py", line 46, in setCredentials
    self._credentials = self.__getCredentials(credentials)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/auth/layer_authentication.py", line 41, in __getCredentials
    password = base64.b64decode(pb64)
  File "/usr/lib/python3.6/base64.py", line 87, in b64decode
    return binascii.a2b_base64(s)
binascii.Error: Incorrect padding
Whatsapp bot crashed with code 1.  Respawning..

**Comment by camiu01** [comment]
@danielcardeenas can you help me pls

**Comment by mikesalmonuk** [comment]
Looks like you're using python3.6 instead of 3.5

**Comment by camiu01** [comment]
i go on 3.5?

**Comment by mikesalmonuk** [comment]
On the frontpage of "https://github.com/danielcardeenas/whatsapp-framework" is says "This needs Python 3.5"

You'll need to install 3.5 instead of 3.6

**Comment by camiu01** [comment]
you can send me the codes for linux are quite new pls

**Comment by camiu01** [comment]
ok i test it

**Comment by mikesalmonuk** [comment]
Sorry, not sure. I use docker on linux and start with `FROM python:3.5` so can't help you with windows emulators. Maybe try google for it.

**Comment by AmitGamingKing** [comment]
Obviously not a problem of Python 3.6 I'm using it on 3.6 and it is running fine...

**Comment by camiu01** [comment]
and then what is the problem?

**Comment by camiu01** [comment]
anywone have the config file I think I was wrong to configure it

**Comment by elchory96** [comment]
There are several things that can cause this problem, what happened to me was that I had the password string in config.py with spaces and also badly stuck from the one I returned yowsup, verify that these data are correctly.

**Comment by elchory96** [comment]
Check this line

https://github.com/danielcardeenas/whatsapp-framework/blob/master/config.py#L3

**Comment by camiu01** [comment]
credentials = dict(
    phone = 3912121212,
    password = 123456,
)

# Your contacts numbers (Framework will sync)
# Add them here
contacts = {
    "cell.num": "name",
}

**Comment by elchory96** [comment]
Remember the quotes in each string of number and password

**Comment by camiu01** [comment]
`  File "run.py", line 4, in <module>
    from yowsup.layers.axolotl.props import PROP_IDENTITY_AUTOTRUST
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_send.py", line 6, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/local/lib/python3.6/dist-packages/python_axolotl-0.1.39-py3.6.egg/axolotl/sessioncipher.py", line 5, in <module>
ModuleNotFoundError: No module named 'Crypto'
Whatsapp bot crashed with code 1.  Respawning..
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from yowsup.layers.axolotl.props import PROP_IDENTITY_AUTOTRUST
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/yowsup/layers/axolotl/layer_send.py", line 6, in <module>
    from axolotl.sessioncipher import SessionCipher
  File "/usr/local/lib/python3.6/dist-packages/python_axolotl-0.1.39-py3.6.egg/axolotl/sessioncipher.py", line 5, in <module>
ModuleNotFoundError: No module named 'Crypto'
Whatsapp bot crashed with code 1.  Respawning..` now give this error lol

**Comment by elchory96** [comment]
Test using the command

`pip3 install yowsup2`

**Comment by camiu01** [comment]
`-bash: pip3: command not found` @elchory96 form cmd

**Comment by elchory96** [comment]
Are you in linux?

**Comment by elchory96** [comment]
In your terminal, execute the following commands

`sudo curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py`

`sudo python3 get-pip.py`

**Comment by camiu01** [comment]
emulator

**Comment by AmitGamingKing** [comment]
Just a normal module not found error I assume that you didn't run ``./setup.sh`` at beginning. Run this if still problem persist then use ``pip3 install blinker`` 

A simpler way to get pip3 is ``sudo apt-get install python3-pip``

**Comment by elchory96** [comment]
> Just a normal module not found error I assume that you didn't run `./setup.sh` at beginning. Run this if still problem persist then use `pip3 install blinker`
> 
> A simpler way to get pip3 is `sudo apt-get install python3-pip`

You're right, if not I always try to give that option because the apt-get or yum command or any other that does not have it installed, I avoid the explanation of the installation of those commands.

**Comment by camiu01** [comment]
`
sudo yowsup-cli registration --requestcode sms --phone 1356594327 -cc 1 -E android
usage: registration [-h] [-v] [-d] [--help-config] [-c CONFIG]
                    [-E {android,s40}] [-m MCC] [-n MNC] [-p PHONE] [-C CC]
                    [-r (sms|voice)] [-R code]
registration: error: unrecognized arguments: 1
`
is a american voip whi I have this problem

**Comment by fckyou-hue** [comment]
😂

**Comment by marlos7** [comment]
Looks like has been discontinued, there's a good project I'm using!
https://github.com/jonalan7/Hydra-bot
