### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by hurradieweltgehtunter** [danielcardeenas/whatsapp-framework#254]
Hi,

I set up the bot some weeks ago and all went nicely. Now I wanted to start again and it fails ond signup and installation.

```
sudo ./setup.sh
Installing yowsup libraries
--------------------------
zip_safe flag not set; analyzing archive contents...
zip_safe flag not set; analyzing archive contents...
yowsup.common.__pycache__.tools.cpython-35: module references __file__
yowsup.yowsup.common.__pycache__.tools.cpython-35: module references __file__
/Users/florianlenz/.pyenv/versions/3.5.0/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'python_requires'
  warnings.warn(msg)
warning: no files found matching '*.c'
warning: no files found matching '*.h'
warning: no files found matching '*.sh'
no previously-included directories found matching 'docs/_static'
warning: no previously-included files found matching '.appveyor.yml'
warning: no previously-included files found matching '.coveragerc'
warning: no previously-included files found matching '.codecov.yml'
warning: no previously-included files found matching '.editorconfig'
warning: no previously-included files found matching '.landscape.yaml'
warning: no previously-included files found matching '.readthedocs.yml'
warning: no previously-included files found matching '.travis'
warning: no previously-included files found matching '.travis/*'
warning: no previously-included files found matching 'tox.ini'
warning: no previously-included files matching '.git*' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
warning: no previously-included files matching '*.so' found anywhere in distribution


The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html
```

also the registration fails (using a previous installed directory):
```
Traceback (most recent call last):
  File "/Users/florianlenz/.pyenv/versions/3.5.0/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/Users/florianlenz/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/Users/florianlenz/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/Users/florianlenz/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/florianlenz/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/Users/florianlenz/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/florianlenz/.pyenv/versions/3.5.0/lib/python3.5/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pillow' distribution was not found and is required by yowsup2
```

any ideas?
thx

**Comment by ezervidarte** [comment]
#pip
#Verifica que versión de pip3 tienes instalado. si es necesario hay que actualizar.
pip3 install --upgrade pip

#Instala los módulos necesarios 
pip3 install pillow
ip3 install python-dateutil
pip3 install argparse

**Comment by magnussolution** [comment]
I had this error, but fix with install pillow, but when I .start.sh I got this error

`Whatsapp bot crashed with code 1.  Respawning..
sudo: python3: command not found`

**Comment by magnussolution** [comment]
si yo ejecuto el comando python3 run.py directo en la terminal me sale 

[Whatsapp] Mac started

pero usando ./start.sh sale 

Whatsapp bot crashed with code 1. Respawning.. sudo: python3: command not found

**Comment by ezervidarte** [comment]
Edita el archivo start.sh y elimina el "sudo". Eso soluciona el arranque.
Actualmente el framework de whatsapp no está funcionando y por eso que solo te mostrará en pantalla "mac started. "

**Comment by ezervidarte** [comment]
#252

**Comment by ezervidarte** [comment]
#252 and #250
