### ISSUE TITLE
No me funciona men :(

### ISSUE THREAD

**Issue by angelcantu84** [danielcardeenas/whatsapp-framework#270]
Hola Daniel.
Principalmente que chido saber que un compa del norte codifico esta herramienta, mil felicitaciones.

Despues de la mamada ahora la pregunta :dagger: 

Resulta que clone tu repo, corri el setup "sudo ./setup.sh" y me dice:

```
$ sudo ./setup.sh
Installing yowsup libraries
--------------------------
Traceback (most recent call last):
  File "setup.py", line 6, in <module>
    from setuptools import find_packages, setup
ModuleNotFoundError: No module named 'setuptools'
Traceback (most recent call last):
  File "setup.py", line 3, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
--------------------------
Configuring modules
--------------------------
[hihelp] All good...
[pokedex] Installing dependencies...
./setup.sh: 10: ./setup.sh: pip3: not found
Error:[127]. Try running it with root privilages
```

Me podrias apoyar men en ver que rollo ?

Saludos desde Reynosa, Tamps :D

**Comment by Ludim** [comment]
Hola, ¿has probado instalando "setuptools" antes de ejecutar el script?
https://stackoverflow.com/questions/14426491/python-3-importerror-no-module-named-setuptools
