### ISSUE TITLE
Bot is not replying in groups .

### ISSUE THREAD

**Issue by MockArch** [danielcardeenas/whatsapp-framework#30]
can i anyone tell how to make bot active in group as well??

**Comment by sealabr** [comment]
try newest commits ... mine is working..

**Comment by MockBond** [comment]
My number got blocked, is there any solution ???

**Comment by andremacola** [comment]
Problem in groups here:

```
AttributeError: 'NoneType' object has no attribute 'getChild'
Whatsapp bot crashed with code 1.  Respawning..
```

**Comment by danielcardeenas** [comment]
@andremacola Can you please post the stack

**Comment by andremacola** [comment]
@danielcardeenas the problem occurs when I don't have all the contacts within the group inside config file

**Comment by danielcardeenas** [comment]
Please send me the error messages, the error stack or something I can work with if you see the error again

**Comment by andremacola** [comment]
`Env not set, setting it to s40
Unhandled message
[Whatsapp] Mac started

sender_key_distribution_message {
groupId: "559881608338-1383459139@g.us"
axolotl_sender_key_distribution_message: "3\010\370\211\265\345\001\020\000\032 \267"\303\324\245%\247\362T)\362\204= \213C+\335\014e\225f\243-:DP\361T\332\024"!\005\K\357"\262\2779\001\034\362\350s\241\302\ru%=m\217\355YE\021!\254\230\332\246dt"
}

(b'\x12n\n\x1c559881608338-1383459139@g.us\x12N3\x08\xf8\x89\xb5\xe5'
b'\x01\x10\x00\x1a \xb7"\xc3\xd4\xa5%\xa7\xf2T)\xf2\x84= \x8bC+\xdd\x0c'
b'e\x95f\xa3-:DP\xf1T\xda\x14"!\x05\K\xef"\xb2\xbf9\x01\x1c\xf2\xe8'
b's\xa1\xc2\ru%=m\x8f\xedYE\x11!\xac\x98\xda\xa6dt')
Ignoring, send ack
Traceback (most recent call last):
File "run.py", line 57, in 
c.start()
File "run.py", line 38, in start
self.stack.loop(timeout=0.5, discrete=0.5)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/stacks/yowstack.py", line 188, in loop
asyncore.loop(*args, **kwargs)
File "/usr/lib/python3.5/asyncore.py", line 203, in loop
poll_fun(timeout, map)
File "/usr/lib/python3.5/asyncore.py", line 150, in poll
read(obj)
File "/usr/lib/python3.5/asyncore.py", line 87, in read
obj.handle_error()
File "/usr/lib/python3.5/asyncore.py", line 83, in read
obj.handle_read_event()
File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
self.handle_read()
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/network/layer.py", line 102, in handle_read
self.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/network/layer.py", line 110, in receive
self.toUpper(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 79, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
self.processReceived()
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
self.toUpper(oneMessageData)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 79, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
self.toUpper(payload)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 79, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
self.toUpper(node)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 79, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
self.toUpper(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 79, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
self.toUpper(protocolTreeNode)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 79, in toUpper
self.__upper.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 194, in receive
s.receive(data)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 120, in receive
if not self.processIqRegistry(protocolTreeNode):
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/init.py", line 161, in processIqRegistry
successClbk(protocolTreeNode, originalIq)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/layer_base.py", line 51, in onSuccess
entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
Whatsapp bot crashed with code 1. Respawning..
Env not set, setting it to s40
[Whatsapp] Mac started

Yowsdown
`

With default hi module

**Comment by andremacola** [comment]
@danielcardeenas any info about this? Funny thing is that, the error occurs only in one specific group. I did some investigation and tried some fix but with no success.

**Comment by danielcardeenas** [comment]
I havent had time to check on this. But my assumption is because the group is not trusted

**Comment by danielcardeenas** [comment]
Please pull new changes

**Comment by andremacola** [comment]
The error persist with my specific group and now I can't upload media files

`Error occured at transfer [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 167, in run
    ssl_sock.write(stream[:buf])
  File "/usr/lib/python3.5/ssl.py", line 808, in write
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by danielcardeenas** [comment]
Regarding the group issue. Can you try this:
Stop the bot if running
Run the `clean.sh` script.

**Comment by andremacola** [comment]
@danielcardeenas I think my specific group is condemned hehe. I've created a new one with all the people and it's fine.

**Comment by danielcardeenas** [comment]
Gonna close this issue. Regarding the media send error I am well aware of it and will fix it soon.
