### ISSUE TITLE
help with python-flask module send message

### ISSUE THREAD

**Issue by sealabr** [danielcardeenas/whatsapp-framework#35]
Hello I'm trying to develop a module to send messages calling a url like this:

need to set entity somewhere?

http://192.168.50.11:5122/SendPostMessage

```
message_send = Blueprint('main', __name__)

@message_send.route("/SendPostMessage", methods=['GET', 'POST'])
def SendPostMessage():
        mac.send_message_to("teste", "5524992942594")


error.......

Traceback (most recent call last):
  File "/usr/lib64/python3.3/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib64/python3.3/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib64/python3.3/site-packages/flask_restful/__init__.py", line 273, in error_router
    return original_handler(e)
  File "/usr/lib64/python3.3/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/lib64/python3.3/site-packages/flask/_compat.py", line 33, in reraise
    raise value
  File "/usr/lib64/python3.3/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python3.3/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/root/microservicos_multicanal/whatsapp-framework/modules/restful_flask/message_send.py", line 14, in SendPostMessage
    mac.send_message_to("teste", "5524992942594")
  File "/root/microservicos_multicanal/whatsapp-framework/app/mac/mac.py", line 137, in send_message_to
    prepate_answer(entity,jid, disconnect_after)
  File "/root/microservicos_multicanal/whatsapp-framework/app/mac/mac.py", line 37, in prepate_answer
    make_presence(self)
  File "/root/microservicos_multicanal/whatsapp-framework/app/mac/mac.py", line 59, in make_presence
    self.toLower(PresenceProtocolEntity(name=name))
AttributeError: 'NoneType' object has no attribute 'toLower'

```

**Comment by danielcardeenas** [comment]
Please update to the last version. I made a change to fix this case setting the entity as soon as possible

**Comment by sealabr** [comment]
all good!
