### ISSUE TITLE
Help with submenus

### ISSUE THREAD

**Issue by maiconcosta** [danielcardeenas/whatsapp-framework#39]
I would like a help to make submenus, from the menu number "1" I tried using the code below but it did not work, here is my code below:

@signals.message_received.connect
def handle(message):
    # Main menu
    if message.command == "Olá":
        menuPrincipal(message)
    # 1 - Budgeting
    elif message.command == "1":
        orcamentos(message)
    # 2 - Track an order already in progress
    elif message.command == "2":
        pedidoAndamento(message)
    # 3 - Change the date, time or location of the event
    elif message.command == "3":
        alterarPedido(message)
    # 4 - Special Offers
    elif message.command == "4":
        promocoes(message)
    # 5 - Speak to a representative
    elif message.command == "5":
        chamarRepresentante(message)

Below is the orcamentos function that you would like to put as a submenu:

def orcamentos(message):
    mac.send_message(txtOrcamentos, message.conversation)
        # 1 Party kit
    if message.command == "1":
        partyKit(message)
        # 2 Confectionery cake
    elif message.command == "2":
        confCake(message)
        # 3 Salty pie
    elif message.command == "3":
        saltPie(message)
        # 4 Cupcakes
    elif message.command == "4":
        cupcakes(message)
        # 5 Sweets
    elif message.command == "5":
        sweets(message)
        # 6 Salty
    elif message.command == "6":
        salty(message)

**Comment by danielcardeenas** [comment]
Post the stack

**Comment by maiconcosta** [comment]
Sorry, I do not understand.

**Comment by maiconcosta** [comment]
A library that connects via whatstapp, the user types the data via whatsapp. With the menus working, but I'm not able to do submenus.

**Comment by danielcardeenas** [comment]
Error messages, error stack. Whatever I can use to fix it. I need more information to understand the problem

**Comment by andremacola** [comment]
`Env not set, setting it to s40
Unhandled message
[Whatsapp] Mac started

sender_key_distribution_message {
  groupId: "559881608338-1383459139@g.us"
  axolotl_sender_key_distribution_message: "3\010\370\211\265\345\001\020\000\032 \267\"\303\324\245%\247\362T)\362\204= \213C+\335\014e\225f\243-:~DP\361T\332\024\"!\005~\\K\357\"\262\2779\001\034\362\350s\241\302\ru%=m\217\355YE\021!\254\230\332\246dt"
}

(b'\x12n\n\x1c559881608338-1383459139@g.us\x12N3\x08\xf8\x89\xb5\xe5'
 b'\x01\x10\x00\x1a \xb7"\xc3\xd4\xa5%\xa7\xf2T)\xf2\x84= \x8bC+\xdd\x0c'
 b'e\x95f\xa3-:~DP\xf1T\xda\x14"!\x05~\\K\xef"\xb2\xbf9\x01\x1c\xf2\xe8'
 b's\xa1\xc2\ru%=m\x8f\xedYE\x11!\xac\x98\xda\xa6dt')
Ignoring, send ack
Traceback (most recent call last):
  File "run.py", line 57, in <module>
    c.start()
  File "run.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 120, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/__init__.py", line 161, in processIqRegistry
    successClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/layer_base.py", line 51, in onSuccess
    entity = ResultGetKeysIqProtocolEntity.fromProtocolTreeNode(resultNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-1.0-py3.5.egg/yowsup/layers/axolotl/protocolentities/iq_keys_get_result.py", line 88, in fromProtocolTreeNode
    preKeyId = ResultGetKeysIqProtocolEntity._bytesToInt(preKeyNode.getChild("id").getData())
AttributeError: 'NoneType' object has no attribute 'getChild'
Whatsapp bot crashed with code 1.  Respawning..
Env not set, setting it to s40
[Whatsapp] Mac started


Yowsdown
`

With default hi module

**Comment by maiconcosta** [comment]
I do not get error messages, the library simply does not run the submenu.

**Comment by maiconcosta** [comment]
I understand, I'm going to do tests and I'll let you know.
