### ISSUE TITLE
how i can send a message to a number when the bot  start?

### ISSUE THREAD

**Issue by Jhosan7** [danielcardeenas/whatsapp-framework#46]
how can i send a message to a number saying "starting!" when i exec ./start.sh??

**Comment by danielcardeenas** [comment]
You need to listen to the `initialized` signal>

```python
from app.mac import mac, signals

'''
Signals this module listents to:
1. When a message is received (signals.command_received)
==========================================================
'''
@signals.command_received.connect
def handle(entity):
    mac.send_message_to("starting!", "521123456789")
```

**Comment by jersonjunior** [comment]
Not works with me:

python3.5 run.py
Traceback (most recent call last):
  File "run.py", line 56, in <module>
    c = MacStack()
  File "run.py", line 25, in __init__
    .push(MacLayer)\
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/stacks/yowstack.py", line 64, in build
    return YowStack(self.layers, reversed = False, props = self._props)
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/stacks/yowstack.py", line 136, in __init__
    self._construct()
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/stacks/yowstack.py", line 207, in _construct
    inst = s()
  File "/opt/whatsapp-framework/app/layer.py", line 27, in __init__
    signals.initialized.send(self)
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/lib/python3/dist-packages/blinker/base.py", line 267, in <listcomp>
    for receiver in self.receivers_for(sender)]
  File "/opt/whatsapp-framework/modules/hihelp/hihelp.py", line 11, in handle
    mac.send_message_to("starting!", "556198002190")
  File "/opt/whatsapp-framework/app/mac/mac.py", line 137, in send_message_to
    prepate_answer(entity,jid, disconnect_after)
  File "/opt/whatsapp-framework/app/mac/mac.py", line 37, in prepate_answer
    make_presence(self)
  File "/opt/whatsapp-framework/app/mac/mac.py", line 59, in make_presence
    self.toLower(PresenceProtocolEntity(name=name))
AttributeError: 'NoneType' object has no attribute 'toLower'

**Comment by danielcardeenas** [comment]
Please pull new changes

**Comment by jersonjunior** [comment]
Works fine now 👍

**Comment by Jhosan7** [comment]
work for me too, thx!
