### ISSUE TITLE
Media Uploader not working

### ISSUE THREAD

**Issue by andremacola** [danielcardeenas/whatsapp-framework#50]
After the last commit

`Error occured at transfer [Errno 104] Connection reset by peer Traceback (most recent call last): File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 167, in run ssl_sock.write(stream[:buf]) File "/usr/lib/python3.5/ssl.py", line 808, in write return self._sslobj.write(data) File "/usr/lib/python3.5/ssl.py", line 586, in write return self._sslobj.write(data) ConnectionResetError: [Errno 104] Connection reset by peer`

**Comment by danielcardeenas** [comment]
Are u trying to send audio?

**Comment by andremacola** [comment]
jpg images

**Comment by haxsystem** [comment]
I have same problem:

```
Error occured at transfer [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/yowsup2-1.0-py3.6.egg/yowsup/layers/protocol_media/mediauploader.py", line 171, in run
    ssl_sock.write(stream[:buf])
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 888, in write
    return self._sslobj.write(data)
  File "/usr/local/Cellar/python3/3.6.3/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 642, in write
    return self._sslobj.write(data)
BrokenPipeError: [Errno 32] Broken pipe
```

**Comment by danielcardeenas** [comment]
Yeah. Looks like something changed on whatsapp side. I'm gonna dig into the whatsapp web version.

**Comment by galaxyitcenter** [comment]
Same issue with s40 env.

**Comment by andremacola** [comment]
New error after update

`Error occured at transfer json data not found
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 202, in run
    raise Exception("json data not found")
Exception: json data not found`

**Comment by galaxyitcenter** [comment]
any success in image?

**Comment by galaxyitcenter** [comment]
@danielcardeenas i looked in to whatsapp web version in that i can see "?f=j" in post url.
and boundary value are different..

**Comment by vikaspwr** [comment]
@andremacola Even I am facing the same issue while sending the images.
ERROR:yowsup.layers.protocol_media.mediauploader:Error occured at transfer json data not found
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 202, in run
    raise Exception("json data not found")
Exception: json data not found
@danielcardeenas any updates?

**Comment by danielcardeenas** [comment]
This got fixed yesterday. Pull new changes
