### ISSUE TITLE
Error send image

### ISSUE THREAD

**Issue by jersonjunior** [danielcardeenas/whatsapp-framework#51]
def image(message)
    mac.send_image("/home/test/test.png", message.conversation, caption="🇧🇷 Test 🇧🇷" )

./start.sh
[Whatsapp] Mac started

Error occured at transfer [Errno 104] Connection reset by peer
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 167, in run
    ssl_sock.write(stream[:buf])
  File "/usr/lib/python3.5/ssl.py", line 816, in write
    return self._sslobj.write(data)
  File "/usr/lib/python3.5/ssl.py", line 594, in write
    return self._sslobj.write(data)
ConnectionResetError: [Errno 104] Connection reset by peer

**Comment by danielcardeenas** [comment]
I am aware of this error. This is whatsapp end side, I'm still working on this

**Comment by jersonjunior** [comment]
/root/baja.png.enc
Error occured at transfer Header value 204492 must be of type str or bytes, not <class 'int'>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 792, in check_header_validity
    if not pat.match(value):
TypeError: expected string or bytes-like object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_media/mediauploader.py", line 222, in run
    response = requests.post(uploadUrl, data=data, headers=headers)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 110, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 474, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 407, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/lib/python3/dist-packages/requests/models.py", line 303, in prepare
    self.prepare_headers(headers)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 427, in prepare_headers
    check_header_validity(header)
  File "/usr/lib/python3/dist-packages/requests/utils.py", line 796, in check_header_validity
    "not %s" % (value, type(value)))
requests.exceptions.InvalidHeader: Header value 204492 must be of type str or bytes, not <class 'int'

**Comment by danielcardeenas** [comment]
Pull new changes

**Comment by jersonjunior** [comment]
Works fine now!
