### ISSUE TITLE
Error on decoding

### ISSUE THREAD

**Issue by MagnusIIIBR** [danielcardeenas/whatsapp-framework#6]
Hi, after install all extesions, plug-ins and packages i receiving this error on receive message in bot

```
We've already setup a session for this V3 message, letting bundled message fall through...
DUMP:

!hi
['\n', '\x03', '!', 'h', 'i']
[10, 3, 33, 104, 105]
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\protobuf-3.2.0-py3.4.egg\google\protobuf\internal\python_message.py", line 1062, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "C:\Python34\lib\site-packages\protobuf-3.2.0-py3.4.egg\google\protobuf\internal\python_message.py", line 1084, in InternalParse
    (tag_bytes, new_pos) = local_ReadTag(buffer, pos)
  File "C:\Python34\lib\site-packages\protobuf-3.2.0-py3.4.egg\google\protobuf\internal\decoder.py", line 181, in ReadTag
    while six.indexbytes(buffer, pos) & 0x80:
TypeError: unsupported operand type(s) for &: 'str' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\SQEST128\Desktop\MacBot-master\run.py", line 53, in <module>
    c.start()
  File "C:\Users\SQEST128\Desktop\MacBot-master\run.py", line 44, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\stacks\yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "C:\Python34\lib\asyncore.py", line 208, in loop
    poll_fun(timeout, map)
  File "C:\Python34\lib\asyncore.py", line 153, in poll
    read(obj)
  File "C:\Python34\lib\asyncore.py", line 87, in read
    obj.handle_error()
  File "C:\Python34\lib\asyncore.py", line 83, in read
    obj.handle_read_event()
  File "C:\Python34\lib\asyncore.py", line 442, in handle_read_event
    self.handle_read()
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\network\layer.py", line 102, in handle_read
    self.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\network\layer.py", line 110, in receive
    self.toUpper(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\stanzaregulator\layer.py", line 29, in receive
    self.processReceived()
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\stanzaregulator\layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\auth\layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\coder\layer.py", line 35, in receive
    self.toUpper(node)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\logger\layer.py", line 14, in receive
    self.toUpper(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\axolotl\layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\__init__.py", line 76, in toUpper
    self.__upper.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\__init__.py", line 189, in receive
    s.receive(data)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\axolotl\layer_receive.py", line 41, in receive
    self.onMessage(protocolTreeNode)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\axolotl\layer_receive.py", line 74, in onMessage
    self.handleEncMessage(protocolTreeNode)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\axolotl\layer_receive.py", line 86, in handleEncMessage
    self.handlePreKeyWhisperMessage(node)
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\axolotl\layer_receive.py", line 129, in handlePreKeyWhisperMessage
    self.parseAndHandleMessageProto(pkMessageProtocolEntity, plaintext[:-padding])
  File "C:\Python34\lib\site-packages\yowsup2-2.5.0-py3.4.egg\yowsup\layers\axolotl\layer_receive.py", line 171, in parseAndHandleMessageProto
    m.ParseFromString(serializedData)
  File "C:\Python34\lib\site-packages\protobuf-3.2.0-py3.4.egg\google\protobuf\message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "C:\Python34\lib\site-packages\protobuf-3.2.0-py3.4.egg\google\protobuf\internal\python_message.py", line 1068, in MergeFromString
    raise message_mod.DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
Pressione qualquer tecla para continuar. . .



```

**Comment by XxStR** [comment]
Did you solve it?

**Comment by MagnusIIIBR** [comment]
no :(

**Comment by legendary902** [comment]
@MagnusIIIBR apenas vem skype --> legendary.902

**Comment by danielcardeenas** [comment]
This happens when the bot receives a reply-type message or a message with a @tag. Currently is not supported.

_Also not sure if this code will work on windows_
