### ISSUE TITLE
KeyError: "Couldn't find field com.whatsapp.proto.ImageMessage.file_enc_sha256"

### ISSUE THREAD

**Issue by ChrisB0701** [danielcardeenas/whatsapp-framework#65]
Hi and thanks for the great framework,

I just installed it on a Debian 4.9 machine following the instructions in the README file. After successfully registering my number, I get the following error when trying to start the bot:

```
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from yowsup.layers.axolotl.props import PROP_IDENTITY_AUTOTRUST
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/axolotl/layer_send.py", line 1, in <module>
    from yowsup.layers.protocol_messages.proto.wa_pb2 import *
  File "/usr/local/lib/python3.5/dist-packages/yowsup2-2.5.2-py3.5.egg/yowsup/layers/protocol_messages/proto/wa_pb2.py", line 216, in <module>
    options=None),
  File "/usr/local/lib/python3.5/dist-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field com.whatsapp.proto.ImageMessage.file_enc_sha256"
Whatsapp bot crashed with code 1.  Respawning..
```

Do you have any ideas, what's wrong here? Thanks in advance!

**Comment by danielcardeenas** [comment]
This happens when you try to send a messsage?

**Comment by danielcardeenas** [comment]
Please pull new changes and retest

**Comment by ChrisB0701** [comment]
I got the error when executing start.sh, but now - after your changes - it's working. Thank you very, very much!
