### ISSUE TITLE
Thearding Issue

### ISSUE THREAD

**Issue by ventrixcode** [danielcardeenas/whatsapp-framework#74]
I try to loop a function in a thread with

`    threading.Thread(target=heron).start()`

this is the Code I want to execute:
`def heron():
    print('Doing something imporant in the background')
    time.sleep(5)
    if (time.strftime("%H") >= "6"):
        mac.send_message("49xxxxxxxxxxx@s.whatsapp.net", "Good Morning")`

But after 10 Seconds I get 

`Traceback (most recent call last):
  File "run.py", line 57, in <module>
    c.start()
  File "run.py", line 38, in start
    self.stack.loop(timeout=0.5, discrete=0.5)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/stacks/yowstack.py", line 188, in loop
    asyncore.loop(*args, **kwargs)
  File "/usr/lib/python3.5/asyncore.py", line 203, in loop
    poll_fun(timeout, map)
  File "/usr/lib/python3.5/asyncore.py", line 150, in poll
    read(obj)
  File "/usr/lib/python3.5/asyncore.py", line 87, in read
    obj.handle_error()
  File "/usr/lib/python3.5/asyncore.py", line 83, in read
    obj.handle_read_event()
  File "/usr/lib/python3.5/asyncore.py", line 423, in handle_read_event
    self.handle_read()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 102, in handle_read
    self.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/network/layer.py", line 110, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 29, in receive
    self.processReceived()
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/stanzaregulator/layer.py", line 49, in processReceived
    self.toUpper(oneMessageData)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/auth/layer_crypt.py", line 65, in receive
    self.toUpper(payload)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/coder/layer.py", line 35, in receive
    self.toUpper(node)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/logger/layer.py", line 14, in receive
    self.toUpper(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_control.py", line 44, in receive
    self.toUpper(protocolTreeNode)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 79, in toUpper
    self.__upper.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 194, in receive
    s.receive(data)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_send.py", line 119, in receive
    if not self.processIqRegistry(protocolTreeNode):
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/__init__.py", line 163, in processIqRegistry
    errorClbk(protocolTreeNode, originalIq)
  File "/usr/local/lib/python3.5/dist-packages/yowsup/layers/axolotl/layer_base.py", line 81, in onError
    errorClbk(errorNode, getKeysEntity)
TypeError: <lambda>() takes 0 positional arguments but 2 were given
`

Thank you & Have a great Day / Night

**Comment by sealabr** [comment]
try to change in run.py

`self.stack.loop(timeout=0.5, discrete=0.5)`

to
`threading._start_new_thread(self.stack.loop, tuple((0.5, 0.5)))`

you need to import threading

**Comment by SPWC** [comment]
I definitely got this working before, but I threaded the function call under specific messages so when the message comes through, the thread d does some work in the background.
I'll dig out the code later on for you.
@sealabr doesn't that just run the whole framework in one thread (instead of multiple whole instances/mutiple background functions)?

**Comment by SaadeMotion** [comment]
Hey @SPWC  can you send me an example on how you did that?

**Comment by ventrixcode** [comment]
> I'll dig out the code later on for you.

@SaadeMotion Just wait? ^^

**Comment by SPWC** [comment]
```
from threading import Thread
from app.mac import mac, signals
from app.utils import helper

'''
Main funciton, all happens after this
'''
@signals.command_received.connect
def handle(message):
    '''
    collects in messages and start thread for each action
    '''
    if helper.is_command(message.text) and message.command.lower() == "help":
        Thread(target=help, args=(message,)).start()
    else:
        return
'''
Actual module code
==========================================================
'''
def help(message):
    answer ='foo'
    mac.send_message(answer, message.conversation)
```

**Comment by ventrixcode** [comment]
@sealabr With this the Bot isnt starting.

**Comment by admill1519** [comment]
@SPWC I have a function with the infinite loop which checks the DateTime to send a message to users as a notification or reminder for something. If I run the function on message.received or message.command this framework only execute the one function and other function doesn't work. It depends on which function I call earlier in the run.py file inside if statement. Please help.
