### ISSUE TITLE
getting error as No module named axolotl_curve25519

### ISSUE THREAD

**Issue by serkandemirhan** [danielcardeenas/whatsapp-framework#8]
c:\test\macbot>python run.py
Traceback (most recent call last):
  File "run.py", line 4, in <module>
    from yowsup.layers.axolotl.props import PROP_IDENTITY_AUTOTRUST
  File "C:\Python27\lib\site-packages\yowsup2-2.5.2-py2.7.egg\yowsup\layers\axolotl\__init__.py", line 1, in <module>
    from .layer_send import AxolotlSendLayer
  File "C:\Python27\lib\site-packages\yowsup2-2.5.2-py2.7.egg\yowsup\layers\axolotl\layer_send.py", line 3, in <module>
    from yowsup.layers.axolotl.protocolentities import *
  File "C:\Python27\lib\site-packages\yowsup2-2.5.2-py2.7.egg\yowsup\layers\axolotl\protocolentities\__init__.py", line 3, in <module>
    from .iq_keys_get_result import ResultGetKeysIqProtocolEntity
  File "C:\Python27\lib\site-packages\yowsup2-2.5.2-py2.7.egg\yowsup\layers\axolotl\protocolentities\iq_keys_get_result.py", line 5, in <module>
    from axolotl.identitykey import IdentityKey
  File "build\bdist.win-amd64\egg\axolotl\identitykey.py", line 3, in <module>
  File "build\bdist.win-amd64\egg\axolotl\ecc\curve.py", line 8, in <module>
ImportError: No module named axolotl_curve25519

**Comment by danielcardeenas** [comment]
This happens due to axolotl_curve25519 not being installed.
Follow the setup in the **README** file
