### ISSUE TITLE
yowsup-cli demos - error

### ISSUE THREAD

**Issue by msm2k11** [danielcardeenas/whatsapp-framework#97]
I try to send manually a message for test but get following error

**version:**
Python 3.6.4+
yowsup-cli v2.0.15
Using yowsup v2.5.2

**cmd:**
yowsup-cli demos -c /usr/local/bin/whatsapp-framework_1/config.py -E android -s 49XXXXX "Das ist ein Test" -d

**out:**
DEBUG:yowsup.env.env:Current env changed to android
Traceback (most recent call last):
  File "/usr/local/bin/yowsup-cli", line 4, in <module>
    __import__('pkg_resources').run_script('yowsup2==2.5.2', 'yowsup-cli')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 368, in <module>
    if not parser.process():
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 272, in process
    self.startSendClient()
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 315, in startSendClient
    credentials = self._getCredentials()
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 283, in _getCredentials
    config = self.getConfig(self.args["config"])
  File "/usr/local/lib/python3.6/dist-packages/yowsup2-2.5.2-py3.6.egg/EGG-INFO/scripts/yowsup-cli", line 72, in getConfig
    val = prep[1].strip()
IndexError: list index out of range

**Comment by msm2k11** [comment]
Solved. I used a false config-file.
